<?php
define('DB_SERVER','YOUR_DB_SERVER_LOCATION');
define('DB_USERNAME','YOUR_DB_USERNAME');
define('DB_PASSWORD','YOUR_DB_PASSWORD');
define('DB_NAME','YOUR_DB_NAME');
define('GOOGLE_MAP_JAVASCRIPT_API','YOUR_GOOGLE_MAP_API_KEY');
define('FMFU_DOMAIN','YOUR_DOMAIN');
?>
